version: '3'

services:
   web:
     depends_on:
       - db
     image: llslim/docker-apache-php:legacy
     volumes:
       - ../../workshop:/var/www/html
       - ../../archive:/var/www/archive
       - ./conf/apache/sites-available:/etc/apache2/sites-available
       # - ./conf/msmtp/msmtprc:/etc/msmtprc
       #- ./conf/php/default.ini:/usr/local/etc/php/conf.d/default.ini
      # - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
     ports:
       - 80:80
       #- 9000:9000
     restart: always
     environment:
       XDEBUG_CONFIG: "idekey=xdebug.Atom remote_host=192.168.1.135"

   db:
     image: mysql:5.7
     volumes:
       - ./conf/mysql:/etc/mysql/conf.d
       - ../../archive/databases:/docker-entrypoint-initdb.d
#       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: myroot
       MYSQL_DATABASE: mydatabase
       MYSQL_USER: myuser
       MYSQL_PASSWORD: mypassword

   mail:
     image: mailhog/mailhog
     ports:
       - 83:8025
     restart: always


   pma:
     image: phpmyadmin/phpmyadmin
     ports:
       - 84:80
     restart: always

# volumes:
#    mail_sbin:
